metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

rpc_secret = "a3f1c9e8b2d4f6a7c8e9d0b1a2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"

[s3_api]
api_bind_addr = "0.0.0.0:3900"
s3_region = "garage"